---
- hosts: dev[0]
  user: ansadmin
  become: yes
  become_user: root
  connection: ssh

  tasks:
    - name: install httpd service
      yum:
        name: httpd
        state: present
        update_cache: yes
      notify: restart httpd
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

