---
- hosts: dev[0]
  user: ansadmin
  become: yes
  become_user: root
  connection: ssh
  
  tasks:
      - name: install httpd
        yum: 
          name: httpd
          state: present

      - name: service
        service:
          name: httpd
          state: started
